### ISSUE TITLE
[v0.9.4] Failed to build project with min sdk 23

### ISSUE THREAD

**Issue by victorlapin** [d4rken/RxShell#14]
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing eu/darken/rxshell/process/RxProcess.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

**Comment by d4rken** [comment]
You might have to add

```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

due to lambdas used in the library.

I'm using it on minSDK 16 without issues.

**Comment by victorlapin** [comment]
Did the trick, thanks. May be worth adding to the readme
