### ISSUE TITLE
How to input on terminal waiting response

### ISSUE THREAD

**Issue by victorjaviermartin** [d4rken/RxShell#46]
Hi, I'm trying your library, but testing with some commands like adb pair, after launching it, the terminal ask user to input a number:

```
C:\Android\sdk\platform-tools>adb pair localhost:12333
Enter pairing code:
```

How it is possible to wait this response and writing something to continue. Calling like the next, keeps the proccess running without exit.

```
private fun rxshellOpenClose(command: List<String>): Cmd.Result? {
        val session = RxCmdShell.builder().build().open().blockingGet()
        val resultBlocking = Cmd.builder(command).execute(session)      // Blocking
        session.close()
        return resultBlocking
    }
```

thank you @d4rken

**Comment by d4rken** [comment]
The library is not designed for interactive input, but can get the input and output streams from the session. I don't have any examples on hand though.

**Comment by victorjaviermartin** [comment]
Thank you @d4rken
